spring.application.name=backend
spring.graphql.graphiql.enabled=true

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/fitme
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.auth.jwt-secret=ZmFjNmQ0YzRlMTUwZTJjZjBiYjkwNTA0NDMzOTYwNjNkODQ1NWE0YjYyMWM4MmZkYjQzZjE4NGM3NGRmZDM2NQ==
app.auth.jwt-expiration-ms=86400000